---
title: "Week 9 Final Project Submission"
author: "Wu Xingyi (Kyra)"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Week 9 Updated Topic Choice

## What Is The Topic That You Have Finalized?
The topic I have finalized for my project is an in-depth analysis of McDonald's meals, with a specific focus on their nutritional content, pricing, and the geographical distribution of McDonald's stores. This research aims to examine the nutritional value of popular menu items, such as Big Macs, and how their prices vary across different locations, providing insights into the relationship between menu offerings, nutrition, and cost-effectiveness.

## What Are The Data Sources That You Have Curated So Far?

### Nutrition Facts for McDonald's Menu
<br>
https://www.kaggle.com/datasets/mcdonalds/nutrition-facts

### Big Mac Prices
<br>
https://www.kaggle.com/datasets/vittoriogiatti/bigmacprice/data

### APAC-McDelivery-Menu-Logger
<br>
https://github.com/schmwong/APAC-McDelivery-Menu-Logger

### Data-mcdonalds-nutrition
<br>
https://github.com/tsterbak/data-mcdonalds-nutritionfacts/blob/master/workbooks/pffy-data-mcdonalds-nutrition-facts.xlsx

# Old Topic Choice
<br>
<br>
### What Is The Topic That You Have Finalized?
<br>
<br>
The topic that I have decided on is the Global Food Paradox. In a world where vast feasts and debilitating famines coexist, the global food paradox challenges us. We're awash in food production yet mired in hunger.  The paradox highlights the stark contrast between regions and communities with an overabundance of food, often leading to issues like over consumption and food waste, while other areas suffer from chronic hunger and malnutrition. As I do not want the data to be too infinitely large, I am thinking of utilising continental data. I am also not too sure how much I can include, so I may do away with the environmental impact and animal welfare part if there is too much. Also, I will definitely reduce the data size as I go along the project because I forsee that I would be trying to pick and choose the more relevant ones. 

### What Are The Data Sources That You Have Curated So Far?
<br>
<br>
<br>
So far, I have managed to get the following data sources which I think are quite interesting to look at. Of course I do not think I will be using everything for the final project but the story I hope to tell would be along the lines of 

# **Food Production**

### Per capita kilocalorie supply from all foods per day, 1961
https://ourworldindata.org/explorers/global-food?time=earliest&facet=none&pickerSort=asc&Food=Total&Metric=Production&Per+Capita=false

# Environmental Impact

### Global emissions from food by life-cycle stage, Total GHGs
https://ourworldindata.org/grapher/food-emissions-life-cycle

### Freshwater withdrawals per kilogram of food product
https://ourworldindata.org/grapher/water-withdrawals-per-kg-poore

### Carbon opportunity costs per kilogram of food
https://ourworldindata.org/grapher/carbon-opportunity-costs-per-kilogram-of-food

### Land use per kilogram of food product
https://ourworldindata.org/grapher/land-use-per-kg-poore

### Greenhouse gas emissions per kilogram of food product
https://ourworldindata.org/grapher/ghg-per-kg-poore

### Scarcity-weighted water use per kilogram of food product
https://ourworldindata.org/grapher/scarcity-water-per-kg-poore

# Animal Welfare
### Number of land animals slaughtered for meat per year, 1961 to 2021
https://ourworldindata.org/explorers/animal-welfare?facet=none&country=OWID_WRL~USA~CHN~IND~BRA~GBR&Metric=Animals+slaughtered&Animal=All+land+animals+(total)&Per+person=false

### Projected habitat loss for all species in 2050: Business-as-usual
https://ourworldindata.org/explorers/habitat-loss

# World Hunger
### Share of population that cannot afford a healthy diet, 2021
https://ourworldindata.org/food-prices

### Number of people that cannot afford a nutrient adequate diet, 2017
https://ourworldindata.org/grapher/number-nutritional-diet-unaffordable

### Number of people that cannot afford a calorie sufficient diet, 2017
https://ourworldindata.org/grapher/number-calorie-diet-unaffordable

<br>



