---
title: "Week 9 Final Project Submission"
author: "Wu Xingyi (Kyra)"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Questions
<br>
<br>

### What is the question that you are going to answer? (Answer: One sentence that ends with a question mark that could act like the title of your data story)
<br>
<br>
Can our world sustain the paradox of abundance and scarcity – where some are overweight, and food is wasted, while others suffer from hunger and environmental pollution?

### Why is this an important question? (Answer: 3 sentences, each of which has some evidence, e.g., “According to the United Nations...” to justify why the question you have chosen is important)
<br>
<br>
Each year, the Food and Agriculture Organization (FAO) calculates that approximately **one-third of the food produced for human consumption globally is lost or wasted,** not only squandering the chance to enhance global food security but also to reduce the environmental footprint and resource utilization within food chains. (Link: https://www.fao.org/3/i3347e/i3347e.pdf)
<br>
<br>
The UN reports that global hunger crisis worsened in 2020 due to the COVID-19 pandemic, where the percentage of undernourished people increased to approximately 9.9% in 2020, up from 8.4% the previous year. Considering the statistical margin of error, it is estimated that between 720 and 811 million individuals worldwide experienced hunger in 2020. (Link: https://www.un.org/sustainabledevelopment/hunger/)
<br>
<br>
According to IPCC research, despite there being over 800 million people experiencing undernourishment — 151 million children under the age of five are stunted, 613 million women and girls between the ages of 15 to 49 are afflicted by iron deficiency — there is a staggering 2 billion adults are grappling with issues related to being overweight or obese. (Link: https://www.ipcc.ch/srccl/chapter/chapter-5/)
<br>
<br>
<br>

# **Data**
### Which rows and columns of the dataset will be used to answer this question? (Answer: Actual names of the variables in the dataset that you plan to use).

### Per capita kilocalorie supply from all foods per day
*This measures the quantity that is available for consumption at the end of the supply chain. It does not account for consumer waste, so the quantity that is actually consumed may be lower than this value.*
<br>
Columns:Country, Year, Population, Food supply (kcal per capita per day)
Rows: Continent Rows (Africa, Asia), United States, China, World
https://ourworldindata.org/explorers/global-food?time=earliest&facet=none&pickerSort=asc&Food=Total&Metric=Production&Per+Capita=false

### Food Loss Index
*The Food Loss Index measures the percentage of food lost from the farm level up until retail. It is compared to percentage losses in 2015. Values greater than 100 show increased waste since 2015; lower values indicate a decrease.*
<br>
Columns Entity	Code	Year	12.3.1 - Global food loss index - AG_FLS_INDEX
Rows: Continent Rows (Africa, Asia), United States, China, World
https://ourworldindata.org/grapher/global-food-loss-index

### Share of the population that is undernourished
*Share of individuals that have a daily food intake that is insufficient to provide the amount of dietary energy required to maintain a normal, active, and healthy life.*
<br>
Columns: Entity, Code, Year, Prevalence of undernourishment (% of population)
Rows:  Continent Rows (Africa, Asia), United States, China, World
https://ourworldindata.org/hunger-and-undernourishment

### Global Hunger Index
*The Global Hunger Index tries to capture the multidimensional nature of hunger by calculating an index score from four key hunger indicators. It is measured on a 100-point scale where 0 is the best score (no hunger) and 100 is the worst.*
<br>
Columns: Entity, Code,	Year,	Global Hunger Index
Rows:  Continent Rows (Africa, Asia), United States, China, World
https://ourworldindata.org/grapher/global-hunger-index

### Challenges: Combining all the data set into 1 might be rather tough, and also for the first data set,  I want to be able to include the codes for the countries also so that is another challenge I forsee. Furthermore, trying to incorporate the Shiny applicaion to this has been rather challenging. 
<br>



