---
title: "McDonald's :^)"
author: "Kyra Wu"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(sf)
library(rnaturalearth)
```
## Reading in data

```{r}
setwd("//Users/kyrawu/kyraxwu.github.io/McDonalds/DataSet/APAC mcd menus")
df = read_csv("[2023-11-03 07_37_15] mcd-api-in.csv")
df = df %>% mutate(`Price (USD)` = round(`Price (INR)`*0.0120268, 2) ) #fixing calculation error in data
write_csv(df, "[2023-11-03 07_37_15] mcd-api-in.csv")
```

##apac_menus
```{r}
setwd("/Users/kyrawu/kyraxwu.github.io/McDonalds/DataSet")
bmi = read_csv("BigmacPrice.csv")
outlets = read_csv("most mcdonalds countries 2022 - Sheet1.csv")
nutrition = read_xlsx("pffy-data-mcdonalds-nutrition-facts.xlsx", sheet = 1)
setwd("/Users/kyrawu/kyraxwu.github.io/McDonalds/DataSet/APAC mcd menus")
csv_files=list.files(pattern = "*.csv$")
apac_menus = NULL

for (file in csv_files) {
  df <- read.csv(file, stringsAsFactors = FALSE)
  required_columns <- c("Territory", "Menu.Item", "Price..USD.", "Category")
  # Check if the "Menu" column exists, if not, create it with NA values
  if(!("Menu" %in% names(df))) {
    df$Menu <- NA  # Add the Menu column with NA values
  }
  df <- df[, c(required_columns, "Menu"), drop = FALSE]
  # Bind this dataframe to the merged dataframe
  if (is.null(apac_menus)) {
    apac_menus <- df
  } else {
    apac_menus <- rbind(apac_menus, df)
  }
}
setwd("/Users/kyrawu/kyraxwu.github.io/McDonalds/DataSet")
names(apac_menus) = c("territory", "menu item", "price", "category", "menu")
write_csv(apac_menus, "apac_menus.csv")

```

##outlets data
```{r}
#install.packages("countrycode")
#install.packages("maps")
library(countrycode)
library(maps)

# Add country code
outlets <- outlets %>%
  mutate(country_code = countrycode(Country, "country.name", "iso3c"),
         outlets_per_mil = `Number of Restaurants per Million Population`,
         num_outlets = `Number of Restaurants`) %>%
  select(-`Number of Restaurants per Million Population`, -`Number of Restaurants`)

# Create a lookup table for latitudes and longitudes
world_cities <- maps::world.cities %>%
  distinct(country.etc, lat, long) %>%
  rename(Country = country.etc)
world_cities <- world_cities %>%
  mutate(Country = case_when(
    Country == "Bahamas" ~ "The Bahamas",
    Country == "Korea South" ~ "South Korea",
    TRUE ~ Country
  ))

outlets <- left_join(outlets, world_cities, by = "Country")
centroids <- outlets %>%
  group_by(Country) %>%
  summarize(
    centroid_lat = mean(lat, na.rm = TRUE),
    centroid_long = mean(long, na.rm = TRUE)
  )
outlets <- left_join(outlets, centroids, by = "Country") %>% select(-"lat", -"long") %>% distinct()

outlets <- outlets  %>%
    mutate(Country = tolower(Country)) # Ensure country names are in lowercase for matching
world_countries <- ne_countries(scale = "medium", returnclass = "sf")

# Join with your data
outlets <- world_countries %>%
    left_join(outlets, by = c("adm0_a3" = "country_code")) %>% 
    select("name","outlets_per_mil", "num_outlets", "First Opening", "pop_est", "gdp_md_est", "economy", "income_grp", "geometry", "centroid_lat","centroid_long") %>% na.omit()

outlets_wkt <- outlets
outlets_wkt$geometry <- st_as_text(outlets$geometry)


# Write updated dataset
write_csv(outlets_wkt, "outlets.csv")
```






